// 模拟数据库 - 海洋生物物种数据
export const speciesData = [
  {
    id: 1,
    chineseName: '中华白海豚',
    latinName: 'Sousa chinensis',
    phylum: '脊索动物门',
    class: '哺乳纲',
    order: '鲸目',
    family: '海豚科',
    genus: '白海豚属',
    species: '中华白海豚',
    morphology: '体型中等，成体体长2-2.5米。幼豚为深灰色，随年龄增长逐渐变为粉白色。吻部较长，背鳍呈三角形，位于背部中央。',
    habits: '主要栖息于河口和近海浅水区域，以鱼类为主食，常在广东、福建沿海出没。社会性动物，通常以小群体活动。',
    distribution: '华南沿海，主要集中在珠江口水域',
    longitude: 113.5,
    latitude: 22.3,
    protectionLevel: '国家一级',
    endangeredStatus: 'VU',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3d/Chinese_White_Dolphin.jpg/480px-Chinese_White_Dolphin.jpg',
    videoUrl: '',
    references: '《中国海洋生物名录》2023版',
    createdBy: '张教授',
    createdAt: '2024-01-15',
    status: 1
  },
  {
    id: 2,
    chineseName: '绿海龟',
    latinName: 'Chelonia mydas',
    phylum: '脊索动物门',
    class: '爬行纲',
    order: '龟目',
    family: '海龟科',
    genus: '海龟属',
    species: '绿海龟',
    morphology: '背甲呈椭圆形，成体背甲长80-120cm，重量可达100-200kg。背甲呈橄榄绿色至棕色，腹甲黄白色。前肢特化为桨状鳍足。',
    habits: '主要以海草和藻类为食（故名绿海龟）。每年回到出生海滩产卵，一次产卵80-120枚，孵化期约60天。',
    distribution: '热带和亚热带海域，广东惠州、汕尾沿海有分布',
    longitude: 115.2,
    latitude: 22.8,
    protectionLevel: '国家二级',
    endangeredStatus: 'EN',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f5/Green_turtle_swimming_over_coral_reefs_in_Hawaii.jpg/480px-Green_turtle_swimming_over_coral_reefs_in_Hawaii.jpg',
    videoUrl: '',
    references: '《世界自然保护联盟濒危物种红色名录》',
    createdBy: '李研究员',
    createdAt: '2024-02-10',
    status: 1
  },
  {
    id: 3,
    chineseName: '鹦嘴鱼',
    latinName: 'Scaridae sp.',
    phylum: '脊索动物门',
    class: '辐鳍鱼纲',
    order: '鲈形目',
    family: '鹦嘴鱼科',
    genus: '鹦嘴鱼属',
    species: '鹦嘴鱼',
    morphology: '以其鸟喙状的融合齿板著称，体色鲜艳多样，雄性通常比雌性更为艳丽。体长通常30-60cm。',
    habits: '珊瑚礁鱼类，以珊瑚和藻类为食，用喙状牙齿啃食珊瑚，排出的碎屑是热带海滩白沙的主要来源之一。',
    distribution: '南海珊瑚礁区域，西沙、南沙群岛均有分布',
    longitude: 112.3,
    latitude: 16.8,
    protectionLevel: '省级',
    endangeredStatus: 'LC',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c1/Chlorurus_sordidus_1.jpg/480px-Chlorurus_sordidus_1.jpg',
    videoUrl: '',
    references: '《南海鱼类图谱》',
    createdBy: '王老师',
    createdAt: '2024-03-05',
    status: 1
  },
  {
    id: 4,
    chineseName: '珊瑚虫',
    latinName: 'Anthozoa',
    phylum: '刺胞动物门',
    class: '珊瑚纲',
    order: '石珊瑚目',
    family: '鹿角珊瑚科',
    genus: '鹿角珊瑚属',
    species: '鹿角珊瑚',
    morphology: '群体生物，由众多珊瑚虫个体组成。骨骼为碳酸钙质，形态多样，包括分枝状、块状、板状等。',
    habits: '依靠共生藻（虫黄藻）进行光合作用获取营养，同时捕食浮游生物。是珊瑚礁生态系统的核心造礁生物。',
    distribution: '南海珊瑚礁区，水温25-29°C的清澈浅海',
    longitude: 111.5,
    latitude: 17.5,
    protectionLevel: '国际公约',
    endangeredStatus: 'VU',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5e/Coral_reef_at_palmyra.jpg/480px-Coral_reef_at_palmyra.jpg',
    videoUrl: '',
    references: '《中国珊瑚礁状况报告》2022',
    createdBy: '陈教授',
    createdAt: '2024-01-20',
    status: 1
  },
  {
    id: 5,
    chineseName: '马尾藻',
    latinName: 'Sargassum',
    phylum: '褐藻门',
    class: '褐藻纲',
    order: '墨角藻目',
    family: '马尾藻科',
    genus: '马尾藻属',
    species: '海蒿子',
    morphology: '大型褐藻，具有气囊（浮胞）保持漂浮状态，叶状体宽扁，叶缘具锯齿，体长可达数米。',
    habits: '广泛分布于潮间带和亚潮间带，为众多海洋生物提供栖息地和食物来源。',
    distribution: '广东沿海各岸段均有分布',
    longitude: 114.8,
    latitude: 21.5,
    protectionLevel: '无',
    endangeredStatus: 'LC',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/23/Sargassum_brown_algae.jpg/480px-Sargassum_brown_algae.jpg',
    videoUrl: '',
    references: '《中国海藻志》',
    createdBy: '赵学生',
    createdAt: '2024-04-12',
    status: 1
  },
  {
    id: 6,
    chineseName: '布氏鲸',
    latinName: 'Balaenoptera brydei',
    phylum: '脊索动物门',
    class: '哺乳纲',
    order: '偶蹄目',
    family: '须鲸科',
    genus: '须鲸属',
    species: '布氏鲸',
    morphology: '中型须鲸，体长12-15米，背部深灰色，腹部白色。头部有3条平行的纵脊，这是与其他须鲸区别的重要特征。',
    habits: '主要以鱼群、磷虾为食，采用侧身滚转、冲刺等方式捕食。在广东沿海近年多次发现搁浅或活体。',
    distribution: '热带和亚热带海域，广东湛江、茂名近海有记录',
    longitude: 110.5,
    latitude: 21.2,
    protectionLevel: '国家一级',
    endangeredStatus: 'DD',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8b/Bryde%27s_whale_%28Balaenoptera_brydei%29.jpg/480px-Bryde%27s_whale_%28Balaenoptera_brydei%29.jpg',
    videoUrl: '',
    references: '《中国鲸类调查报告》2023',
    createdBy: '张教授',
    createdAt: '2024-05-08',
    status: 1
  },
  {
    id: 7,
    chineseName: '红树林螃蟹',
    latinName: 'Sesarma mederi',
    phylum: '节肢动物门',
    class: '软甲纲',
    order: '十足目',
    family: '方蟹科',
    genus: '相手蟹属',
    species: '无齿相手蟹',
    morphology: '甲壳宽约3cm，近方形，暗褐色或棕红色。螯足左右不对称，善攀爬树木。',
    habits: '典型红树林生物，以落叶、有机碎屑为食，是红树林生态系统物质循环的重要参与者。',
    distribution: '广东雷州半岛、湛江红树林自然保护区',
    longitude: 110.2,
    latitude: 20.9,
    protectionLevel: '无',
    endangeredStatus: 'LC',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/10/Sesarma_mederi.jpg/480px-Sesarma_mederi.jpg',
    videoUrl: '',
    references: '《红树林生态系统研究》',
    createdBy: '李研究员',
    createdAt: '2024-03-22',
    status: 1
  },
  {
    id: 8,
    chineseName: '玳瑁',
    latinName: 'Eretmochelys imbricata',
    phylum: '脊索动物门',
    class: '爬行纲',
    order: '龟目',
    family: '海龟科',
    genus: '玳瑁属',
    species: '玳瑁',
    morphology: '背甲呈心形，覆有棕黄色和棕褐色相间的美丽花纹，吻部弯曲如鹰钩，成体背甲长约60-90cm。',
    habits: '主要以海绵为食，也摄食水母、藻类等。喜栖息于珊瑚礁区域，是珊瑚礁生态系统的重要物种。',
    distribution: '南海热带水域，西沙群岛有繁殖种群',
    longitude: 112.0,
    latitude: 16.5,
    protectionLevel: '国家一级',
    endangeredStatus: 'CR',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/be/Hawksbill_turtle_-_Eretmochelys_imbricata.jpg/480px-Hawksbill_turtle_-_Eretmochelys_imbricata.jpg',
    videoUrl: '',
    references: 'CITES附录I物种',
    createdBy: '陈教授',
    createdAt: '2024-02-28',
    status: 1
  }
]

// 生态系统数据
export const ecosystemData = [
  { id: 1, name: '珊瑚礁生态系统', type: 'coral_reef', description: '热带和亚热带浅海的珊瑚礁区域，生物多样性极为丰富，被称为"海洋中的热带雨林"。', area: '南海', createdAt: '2024-01-01' },
  { id: 2, name: '红树林生态系统', type: 'mangrove', description: '热带和亚热带海岸潮间带的红树林区域，是陆地与海洋的过渡地带，具有防风固浪的重要功能。', area: '广东湛江、雷州半岛', createdAt: '2024-01-01' },
  { id: 3, name: '海草床生态系统', type: 'seagrass', description: '浅海区域的海草草场，是儒艮、海龟等珍稀动物的重要觅食地和栖息地。', area: '广东沿海浅海区', createdAt: '2024-01-01' },
  { id: 4, name: '深海生态系统', type: 'deep_sea', description: '水深超过200米的深海区域，独特的高压、低温、无光环境孕育了特殊的生命形式。', area: '南海深水区', createdAt: '2024-01-01' },
  { id: 5, name: '河口生态系统', type: 'estuary', description: '淡水与海水交汇的河口区域，是众多洄游鱼类和鸟类的重要栖息地。', area: '珠江口、韩江口', createdAt: '2024-01-01' }
]

// 观测记录数据
export const observationData = [
  {
    id: 1,
    title: '珠江口白海豚种群调查',
    observedAt: '2024-03-15 09:30',
    longitude: 113.5,
    latitude: 22.3,
    ecosystemId: 5,
    ecosystemName: '河口生态系统',
    observers: '张教授, 李研究员',
    waterTemp: 22.5,
    salinity: 18.3,
    depth: 5.2,
    weatherCondition: '晴',
    notes: '观测到5只中华白海豚个体，其中包含1只幼豚，群体行为活跃，正在觅食。',
    species: [
      { speciesId: 1, speciesName: '中华白海豚', count: 5, behavior: '觅食' }
    ],
    createdBy: '张教授',
    createdAt: '2024-03-15'
  },
  {
    id: 2,
    title: '惠州绿海龟产卵监测',
    observedAt: '2024-06-20 21:00',
    longitude: 115.2,
    latitude: 22.8,
    ecosystemId: 1,
    ecosystemName: '珊瑚礁生态系统',
    observers: '李研究员, 王老师',
    waterTemp: 28.1,
    salinity: 32.5,
    depth: 0.5,
    weatherCondition: '多云',
    notes: '在后门湾沙滩监测到绿海龟上岸产卵，共记录3个巢穴，每巢约100枚卵。',
    species: [
      { speciesId: 2, speciesName: '绿海龟', count: 3, behavior: '产卵' }
    ],
    createdBy: '李研究员',
    createdAt: '2024-06-20'
  },
  {
    id: 3,
    title: '湛江红树林生态调查',
    observedAt: '2024-04-10 08:00',
    longitude: 110.2,
    latitude: 20.9,
    ecosystemId: 2,
    ecosystemName: '红树林生态系统',
    observers: '陈教授, 赵学生',
    waterTemp: 25.3,
    salinity: 24.1,
    depth: 1.5,
    weatherCondition: '晴',
    notes: '在湛江红树林国家级自然保护区开展综合生态调查，记录到多种底栖生物和鸟类。',
    species: [
      { speciesId: 7, speciesName: '红树林螃蟹', count: 50, behavior: '觅食' }
    ],
    createdBy: '陈教授',
    createdAt: '2024-04-10'
  },
  {
    id: 4,
    title: '西沙群岛珊瑚礁鱼类调查',
    observedAt: '2024-05-18 10:00',
    longitude: 112.3,
    latitude: 16.8,
    ecosystemId: 1,
    ecosystemName: '珊瑚礁生态系统',
    observers: '王老师, 赵学生',
    waterTemp: 29.2,
    salinity: 34.8,
    depth: 8.0,
    weatherCondition: '晴',
    notes: '西沙珊瑚礁潜水调查，记录到鱼类30余种，珊瑚覆盖率约65%。',
    species: [
      { speciesId: 3, speciesName: '鹦嘴鱼', count: 20, behavior: '觅食' },
      { speciesId: 4, speciesName: '珊瑚虫', count: 500, behavior: '固着' }
    ],
    createdBy: '王老师',
    createdAt: '2024-05-18'
  },
  {
    id: 5,
    title: '广东近海布氏鲸监测',
    observedAt: '2024-07-05 14:30',
    longitude: 110.5,
    latitude: 21.2,
    ecosystemId: 4,
    ecosystemName: '深海生态系统',
    observers: '张教授',
    waterTemp: 30.1,
    salinity: 33.2,
    depth: 15.0,
    weatherCondition: '晴',
    notes: '在湛江近海发现布氏鲸群体，共3只，正在进行协作觅食行为，拍摄到大量珍贵影像资料。',
    species: [
      { speciesId: 6, speciesName: '布氏鲸', count: 3, behavior: '觅食' }
    ],
    createdBy: '张教授',
    createdAt: '2024-07-05'
  }
]

// 用户数据
export const userData = [
  { id: 1, username: 'admin', password: 'admin123', role: 'admin', name: '系统管理员', email: 'admin@gdou.edu.cn', avatar: '', status: 1, createdAt: '2024-01-01' },
  { id: 2, username: 'researcher', password: 'research123', role: 'researcher', name: '张教授', email: 'zhang@gdou.edu.cn', avatar: '', status: 1, createdAt: '2024-01-05' },
  { id: 3, username: 'student', password: 'student123', role: 'student', name: '赵学生', email: 'zhao@gdou.edu.cn', avatar: '', status: 1, createdAt: '2024-02-01' },
  { id: 4, username: 'public', password: 'public123', role: 'public', name: '访客用户', email: 'guest@example.com', avatar: '', status: 1, createdAt: '2024-03-01' }
]

// 活动日志
export const activityLog = [
  { id: 1, userId: 2, userName: '张教授', action: '添加物种', target: '中华白海豚', time: '2024-01-15 10:23:45', ip: '192.168.1.100' },
  { id: 2, userId: 2, userName: '张教授', action: '创建观测记录', target: '珠江口白海豚种群调查', time: '2024-03-15 09:35:12', ip: '192.168.1.100' },
  { id: 3, userId: 3, userName: '李研究员', action: '添加物种', target: '绿海龟', time: '2024-02-10 14:20:33', ip: '192.168.1.102' },
  { id: 4, userId: 1, userName: '系统管理员', action: '用户审批', target: '赵学生', time: '2024-02-01 09:00:00', ip: '192.168.1.1' }
]

// 2026-03-27: 优化物种分类数据结构，补充各物种的科属分类注释，提升前端筛选查询效率

// 2026-03-28: 新增观测记录数据字段校验，统一经纬度坐标格式与深度单位，修复数据录入异常问题
